### ISSUE TITLE
1.1.2.3 release checklist

### ISSUE THREAD

**Issue by bbolker** [glmmTMB/glmmTMB#759]
Due September 21.

- [ ] run checks everywhere (win-builder, r-hub, GH actions, locally)
- [x] run reverse dependency checks (OK with `revdepcheck::revdep_check()` as of 14 September on r-devel `2021-07-30 r80684`, BMB's machine; also OK on updated r-devel `2021-09-15 r80901`)
- [x] address [CRAN check problems](https://cran.r-project.org/web/checks/check_results_glmmTMB.html)
   - [r-devel-linux-x86_64-fedora-clang ](https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-clang/glmmTMB-00install.html): `clang` problem, addressed in 6ac4eea
   - [r-patched-solaris-x86](https://www.r-project.org/nosvn/R.check/r-patched-solaris-x86/glmmTMB-00check.html) ?? this is #732; I'm not sure how we can address it (without easy access to a 64-bit Solaris VM ... it works on 32-bit Solaris platform on r-hub ...)
   - [r-release-windows-ix86+x86_64](https://www.r-project.org/nosvn/R.check/r-release-windows-ix86+x86_64/glmmTMB-00install.html) install failure: "Error in library.dynam(lib, package, package.lib) :  DLL 'Rcpp' not found: maybe not installed for this architecture?" (seems like this could be a transient glitch??)
- [x] make sure NEWS is up to date
There doesn't seem to be anything else in the way of low-hanging fruit or new/release-critical bugs ... ?

**Comment by mebrooks** [comment]
I'll start running some checks now.

**Comment by bbolker** [comment]
It seems that CRAN Solaris is actually 32-bit? https://stat.ethz.ch/pipermail/r-package-devel/2021q3/007364.html

**Comment by mebrooks** [comment]
Platform:	Windows Server 2008 R2 SP1, R-release, 32/64 bit seems [ok](https://builder.r-hub.io/status/glmmTMB_1.1.2.3.tar.gz-baee376372ed4ebda0021965884d8589). 

On Platform: Debian Linux, R-patched, GCC I get a [warning](https://builder.r-hub.io/status/glmmTMB_1.1.2.3.tar.gz-dae2440a7be54c3d9e3ba4c57a093344):

```
#> * checking compiled code ... WARNING
23279#> File ‘glmmTMB/libs/glmmTMB.so’:
23280#> Found ‘_ZSt4cerr’, possibly from ‘std::cerr’ (C++)
23281#> Object: ‘glmmTMB.o’
23282#> Found ‘exit’, possibly from ‘exit’ (C)
23283#> Object: ‘glmmTMB.o’
23284#> Compiled code should not call entry points which might terminate R nor
23285#> write to stdout/stderr instead of to the console, nor use Fortran I/O
```

**Comment by bbolker** [comment]
@mebrooks: That's a standard warning caused by using development (GitHub) TMB instead of CRAN TMB.  You can ignore it, or, if you want to be sure, install TMB from CRAN and re-check.

**Comment by bbolker** [comment]
I haven't run tests everywhere, but as far as I can tell we're ready to submit after #762 is merged. We will need to address the three current CRAN check failures carefully in our submission message:

- r-devel-linux-x86_64-fedora-clang: resolved by code patch; this is what prompted the submission in the first place
- r-patched-solaris-x86: we can't replicate this problem on r-hub's Solaris+gcc platform, which as far as we can tell is the same as CRAN's platform for this case (since the package uses Rcpp)
- r-release-windows-ix86+x86_64: looks like a transient glitch on the build platform?

**Comment by bbolker** [comment]
I think I've done everything except (1) test on win-builder (important to see if our tests are still fast/skipping enough stuff to keep CRAN happy!) (2) switch the maintainer back to @mebrooks  in the `DESCRIPTION` file.  Other than that I think we're good to go ... ?

**Comment by bbolker** [comment]
Deadline for resubmission to CRAN is Tuesday.  If I don't hear back I will try to submit this as maintainer tomorrow.

**Comment by mebrooks** [comment]
I uploaded to win-builder just now and I'm running `check --as-cran` on the cluster since I still haven't updated R on my laptop. The good news is that I got a new laptop on Friday and now I need to set it up.

**Comment by mebrooks** [comment]
It seems to be fine on winbuilder, r-hub, and the cluster. I put myself as maintainer in the `DESCRIPTION` file again. It looks like CRAN checks were last updated today. There's an [error on platform: x86_64-w64-mingw32 (64-bit)](https://www.r-project.org/nosvn/R.check/r-devel-windows-x86_64-gcc10-UCRT/glmmTMB-00install.html) that we haven't addressed. The package doesn't compile. Is it enough to write in the submission message that we can't replicate that?

**Comment by bbolker** [comment]
Yes, that looks like a glitch on the testing platform to me ...

**Comment by mebrooks** [comment]
Ok. I submitted it to CRAN. Thanks.

**Comment by bbolker** [comment]
Curious if you've heard anything back. I approved the change-of-maintainer back to Mollie, Uwe Ligges said (at 20 Sep 2021 16:21:44 +0200) "Thanks, reverse dependency checks have been triggered.", but I don't see it in the CRAN queue via `foghorn::cran_incoming("glmmTMB")`, which makes me a little nervous that it bounced for some trivial reason ...

**Comment by kaskr** [comment]
It's already on CRAN I think?

**Comment by bbolker** [comment]
Thanks!

I thought I had bumped the version number all the way to 1.1.3 (it seemed worthwhile since there were actually a few significant albeit minor changes), but either I didn't or it got reverted somehow. NBD.

**Comment by mebrooks** [comment]
Sorry about that. I changed it locally to match the issue name, without looking carefully. I didn't do anything to the `master` branch yet.
